### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [anhpnguyen/form-hwk#1]
I broke it. :cry: It looks like when I try to submit a blank form, I get an `Internal Server Error`. I believe [this resource](http://www.w3schools.com/tags/att_input_required.asp) may help you avoid a blank form being submitted.

Let me know when it's updated and I'll take another look.

**Comment by anhpnguyen** [comment]
Hi Chris! I think I fixed the error, but when I open it on heroku, I get an error that say "assertion 'sys_page_size == 0' failed". I wonder if this is the outstanding issue that you're reminding me for, because the app still opens and works.

**Comment by chrisvfritz** [comment]
Hmm, it's opening up on Heroku just fine for me. Either way, it looks good! I don't see anymore errors. :smiley: :+1:
